/*
 * generated by Xtext 2.12.0.M1
 */
package hu.bme.mit.inf.viewmodel.language.ide


/**
 * Use this class to register ide components.
 */
class ViewModelLanguageIdeModule extends AbstractViewModelLanguageIdeModule {
}
