/*
 * generated by Xtext 2.12.0.M1
 */
package hu.bme.mit.inf.viewmodel.language.formatting2

import org.eclipse.xtext.xbase.formatting2.XbaseFormatter

class ViewModelLanguageFormatter extends XbaseFormatter {
	
}
