/*
 * generated by Xtext 2.12.0.M1
 */
package hu.bme.mit.inf.viewmodel.language


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ViewModelLanguageStandaloneSetup extends ViewModelLanguageStandaloneSetupGenerated {

	def static void doSetup() {
		new ViewModelLanguageStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
